Homework 2
================
Zeheng Wei
2026-09-30

# Problem 1

### Import and clean data

``` r
nyc_subway_entrance_exit_data = read_csv(
  file = "./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
  col_types = cols(
    Route8 = col_character(),
    Route9 = col_character(),
    Route10 = col_character(),
    Route11 = col_character())) |>
  janitor::clean_names() |>
  select(
    line,
    station_name,
    station_latitude,
    station_longitude,
    route1:route11,
    entry,
    vending,
    entrance_type,
    ada) |>
  mutate(
    entry = case_match(
      entry,
      "YES" ~ TRUE,
      "NO" ~ FALSE))
```

### Check the cleaned data

``` r
nyc_subway_entrance_exit_data
```

    ## # A tibble: 1,868 × 19
    ##    line     station_name station_latitude station_longitude route1 route2 route3
    ##    <chr>    <chr>                   <dbl>             <dbl> <chr>  <chr>  <chr> 
    ##  1 4 Avenue 25th St                  40.7             -74.0 R      <NA>   <NA>  
    ##  2 4 Avenue 25th St                  40.7             -74.0 R      <NA>   <NA>  
    ##  3 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  4 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  5 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  6 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  7 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  8 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  9 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ## 10 4 Avenue 53rd St                  40.6             -74.0 R      <NA>   <NA>  
    ## # ℹ 1,858 more rows
    ## # ℹ 12 more variables: route4 <chr>, route5 <chr>, route6 <chr>, route7 <chr>,
    ## #   route8 <chr>, route9 <chr>, route10 <chr>, route11 <chr>, entry <lgl>,
    ## #   vending <chr>, entrance_type <chr>, ada <lgl>

``` r
number_of_entrance_exit_records =
  length(nyc_subway_entrance_exit_data$line)

number_of_retained_variables =
  length(names(nyc_subway_entrance_exit_data))
```

### Dataset description

Each row describes a NYC subway entrance or exit, so stations may appear
more than once. Variables include the line, station name and location,
routes, entry permission, vending, entrance type, and ADA compliance. I
cleaned the column names, kept the requested variables, converted entry
from YES/NO to TRUE/FALSE, and read Route8–Route11 as character columns
for consistent route types. The cleaned data have 1868 rows and 19
columns. They are not tidy yet because routes are spread across 11
columns instead of one variable.

### Distinct stations

``` r
number_of_distinct_stations =
  nyc_subway_entrance_exit_data |>
  distinct(line, station_name) |>
  pull(station_name) |>
  length()
```

There are 465 distinct stations, identified using both line and station
name.

### ADA-compliant stations

``` r
number_of_ada_compliant_stations =
  nyc_subway_entrance_exit_data |>
  filter(ada == TRUE) |>
  distinct(line, station_name) |>
  pull(station_name) |>
  length()
```

For these stations, 84 are ADA compliant.

### Entry without vending

``` r
number_of_entrances_exits_without_vending =
  nyc_subway_entrance_exit_data |>
  filter(vending == "NO") |>
  pull(entry) |>
  length()

number_of_entrances_exits_without_vending_allowing_entry =
  nyc_subway_entrance_exit_data |>
  filter(vending == "NO", entry == TRUE) |>
  pull(entry) |>
  length()

proportion_allowing_entry_without_vending =
  number_of_entrances_exits_without_vending_allowing_entry /
  number_of_entrances_exits_without_vending
```

Among the 183 entrances and exits without vending, 69 allow entry,
giving a proportion of 0.38.

### Routes and A train stations

``` r
nyc_subway_route_data =
  nyc_subway_entrance_exit_data |>
  pivot_longer(
    route1:route11,
    names_to = "route_number",
    names_prefix = "route",
    values_to = "route_name") |>
  drop_na(route_name)

number_of_a_train_stations =
  nyc_subway_route_data |>
  filter(route_name == "A") |>
  distinct(line, station_name) |>
  pull(station_name) |>
  length()

number_of_ada_compliant_a_train_stations =
  nyc_subway_route_data |>
  filter(route_name == "A", ada == TRUE) |>
  distinct(line, station_name) |>
  pull(station_name) |>
  length()
```

I reshaped the routes into `route_number` and `route_name` and removed
empty slots. Using line and station name to identify distinct stations,
the A train serves 60 stations, of which 17 are ADA compliant.

# Problem 2

### Import and clean Mr. Trash Wheel data

``` r
mr_trash_wheel_data =
  readxl::read_excel(
    "./data/202610 Trash Wheel Collection Data.xlsx",
    sheet = "Mr. Trash Wheel",
    range = "A2:N742") |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(
    year = as.integer(year),
    sports_balls = as.integer(round(sports_balls, digits = 0)),
    trash_wheel = "Mr. Trash Wheel")
```

### Import and clean Professor and Gwynnda data

``` r
professor_trash_wheel_data =
  readxl::read_excel(
    "./data/202610 Trash Wheel Collection Data.xlsx",
    sheet = "Professor Trash Wheel",
    range = "A2:M139",
    na = c("", "dive")) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(
    year = as.integer(year),
    trash_wheel = "Professor Trash Wheel")

gwynnda_trash_wheel_data =
  readxl::read_excel(
    "./data/202610 Trash Wheel Collection Data.xlsx",
    sheet = "Gwynnda the Good Wheel of the W",
    range = "A2:L394") |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(
    year = as.integer(year),
    trash_wheel = "Gwynnda")
```

### Combine and check the data

``` r
trash_wheel_collection_data =
  bind_rows(
    mr_trash_wheel_data,
    professor_trash_wheel_data,
    gwynnda_trash_wheel_data)

trash_wheel_collection_data
```

    ## # A tibble: 1,269 × 15
    ##    dumpster month  year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <int> <dttm>                    <dbl>              <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31                 18
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74                 13
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45                 15
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1                  15
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06                 18
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71                 13
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91                  8
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7                  16
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52                 14
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76                 18
    ## # ℹ 1,259 more rows
    ## # ℹ 9 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>, trash_wheel <chr>

``` r
number_of_dumpster_records =
  length(trash_wheel_collection_data$dumpster)
```

### Dataset description

The combined dataset contains 1269 dumpster records from Mr. Trash
Wheel, Professor Trash Wheel, and Gwynnda. Variables include collection
date, weight in tons, volume in cubic yards, homes powered, and trash
item counts. I excluded totals and non-data entries, cleaned column
names, and kept rows with a dumpster number. I rounded Mr. Trash Wheel’s
sports ball counts and converted them to integers, standardized `year`,
and added `trash_wheel` to identify the source. I treated the nonnumeric
value `dive` in Professor’s plastic bottle counts as missing. Missing or
unrecorded measurements remain `NA`.

### Total weight collected

``` r
total_weight_in_tons_collected_by_professor_trash_wheel =
  trash_wheel_collection_data |>
  filter(trash_wheel == "Professor Trash Wheel") |>
  pull(weight_tons) |>
  sum()
```

Across the available records, Professor Trash Wheel collected 294.96
tons of trash.

### Cigarette butts collected by Gwynnda

``` r
total_cigarette_butts_collected_by_gwynnda_in_june_2022 =
  trash_wheel_collection_data |>
  filter(trash_wheel == "Gwynnda", year == 2022, month == "June") |>
  pull(cigarette_butts) |>
  sum()
```

Gwynnda collected 18120 cigarette butts in June 2022.

# Problem 3

### Import and clean baseline demographics

``` r
mci_baseline_imported_data =
  read_csv(
    file = "./data/data_mci/MCI_baseline.csv",
    skip = 1,
    na = c(".", "NA", "")) |>
  janitor::clean_names() |>
  rename(baseline_age = current_age) |>
  mutate(
    sex = case_match(sex, 0 ~ "female", 1 ~ "male"),
    sex = as.factor(sex),
    apoe4 = case_match(apoe4, 0 ~ "non-carrier", 1 ~ "carrier"),
    apoe4 = as.factor(apoe4))

mci_baseline_data =
  mci_baseline_imported_data |>
  filter(is.na(age_at_onset) | age_at_onset > baseline_age)
```

### Baseline participant statistics

``` r
mci_baseline_data
```

    ## # A tibble: 479 × 6
    ##       id baseline_age sex    education apoe4       age_at_onset
    ##    <dbl>        <dbl> <fct>      <dbl> <fct>              <dbl>
    ##  1     1         63.1 female        16 carrier             NA  
    ##  2     2         65.6 female        20 carrier             NA  
    ##  3     3         62.5 male          16 carrier             66.8
    ##  4     4         69.8 female        16 non-carrier         NA  
    ##  5     5         66   male          16 non-carrier         68.7
    ##  6     6         62.5 male          16 non-carrier         NA  
    ##  7     7         66.5 male          18 non-carrier         74  
    ##  8     8         67.2 female        18 non-carrier         NA  
    ##  9     9         66.7 female        16 non-carrier         NA  
    ## 10    10         64.1 female        18 non-carrier         NA  
    ## # ℹ 469 more rows

``` r
number_of_recruited_participants =
  length(mci_baseline_imported_data$id)

number_of_eligible_participants =
  length(mci_baseline_data$id)

number_of_excluded_participants =
  number_of_recruited_participants - number_of_eligible_participants

number_of_participants_who_developed_mci =
  sum(!is.na(mci_baseline_data$age_at_onset))

average_baseline_age =
  mean(mci_baseline_data$baseline_age)

number_of_female_participants =
  sum(mci_baseline_data$sex == "female")

number_of_female_apoe4_carriers =
  sum(mci_baseline_data$sex == "female" & mci_baseline_data$apoe4 == "carrier")

proportion_of_female_participants_with_apoe4 =
  number_of_female_apoe4_carriers / number_of_female_participants
```

### Baseline data description and results

I skipped the description row, cleaned column names, renamed
`current_age` to `baseline_age`, and converted sex and APOE4 status to
labeled factors. I treated `.` as missing onset age and retained these
participants because they remained MCI free throughout follow-up. Each
row represents one participant, with baseline demographics, education,
and MCI onset age.

The original baseline file contains 483 participants. I excluded 4 whose
MCI onset age was at or before their baseline age, leaving 479 eligible
participants. Among this eligible group, 93 developed MCI during
follow-up, and the average baseline age was 65.03 years. Of the 210
women, 63 were APOE4 carriers, giving a proportion of 0.3.

### Import and tidy amyloid data

``` r
mci_amyloid_data =
  read_csv(
    file = "./data/data_mci/mci_amyloid.csv",
    skip = 1,
    na = c(".", "NA", "Na", "")) |>
  janitor::clean_names() |>
  rename(id = study_id) |>
  pivot_longer(
    baseline:time_8,
    names_to = "years_since_baseline",
    values_to = "amyloid_42_40_ratio") |>
  mutate(
    years_since_baseline = case_match(
      years_since_baseline,
      "baseline" ~ 0,
      "time_2" ~ 2,
      "time_4" ~ 4,
      "time_6" ~ 6,
      "time_8" ~ 8))

mci_amyloid_data
```

    ## # A tibble: 2,435 × 3
    ##       id years_since_baseline amyloid_42_40_ratio
    ##    <dbl>                <dbl>               <dbl>
    ##  1     1                    0               0.111
    ##  2     1                    2              NA    
    ##  3     1                    4               0.109
    ##  4     1                    6               0.105
    ##  5     1                    8               0.107
    ##  6     2                    0               0.107
    ##  7     2                    2               0.109
    ##  8     2                    4               0.109
    ##  9     2                    6               0.106
    ## 10     2                    8               0.107
    ## # ℹ 2,425 more rows

``` r
number_of_amyloid_visit_records =
  length(mci_amyloid_data$id)

number_of_participants_in_amyloid_data =
  mci_amyloid_data |>
  distinct(id) |>
  pull(id) |>
  length()

number_of_missing_amyloid_ratios =
  sum(is.na(mci_amyloid_data$amyloid_42_40_ratio))
```

### Amyloid dataset description

I skipped the description row, cleaned column names, renamed `study_id`
to `id`, and treated `NA` and `Na` as missing. Using `pivot_longer()`, I
reshaped the visit columns into time (0, 2, 4, 6, and 8 years since
baseline) and amyloid 42/40 ratio variables. The tidy dataset contains
2435 participant-visit records from 487 participants, with 172 missing
ratios retained as `NA`.

### Check participants appearing in only one dataset

``` r
participants_only_in_baseline_data =
  anti_join(mci_baseline_data, mci_amyloid_data, by = "id") |>
  distinct(id)

participants_only_in_amyloid_data =
  anti_join(mci_amyloid_data, mci_baseline_data, by = "id") |>
  distinct(id)

amyloid_participants_without_original_baseline_data =
  anti_join(mci_amyloid_data, mci_baseline_imported_data, by = "id") |>
  distinct(id)

number_of_participants_only_in_baseline_data =
  length(participants_only_in_baseline_data$id)

number_of_participants_only_in_amyloid_data =
  length(participants_only_in_amyloid_data$id)

number_of_amyloid_participants_without_original_baseline_data =
  length(amyloid_participants_without_original_baseline_data$id)

number_of_excluded_participants_in_amyloid_data =
  number_of_participants_only_in_amyloid_data -
  number_of_amyloid_participants_without_original_baseline_data

participants_only_in_baseline_data
```

    ## # A tibble: 8 × 1
    ##      id
    ##   <dbl>
    ## 1    14
    ## 2    49
    ## 3    92
    ## 4   179
    ## 5   268
    ## 6   304
    ## 7   389
    ## 8   412

``` r
print(participants_only_in_amyloid_data, n = 20)
```

    ## # A tibble: 16 × 1
    ##       id
    ##    <dbl>
    ##  1    72
    ##  2   234
    ##  3   283
    ##  4   380
    ##  5   484
    ##  6   485
    ##  7   486
    ##  8   487
    ##  9   488
    ## 10   489
    ## 11   490
    ## 12   491
    ## 13   492
    ## 14   493
    ## 15   494
    ## 16   495

### Participant matching findings

Comparing the amyloid data with the eligible baseline dataset, 8
participants appear only in baseline and 16 appear only in amyloid. Of
the amyloid-only group, 4 were excluded earlier because they already had
MCI at baseline. Comparing with the original baseline file shows that
the remaining 12 participants have no baseline record. The source files
do not explain the remaining mismatches.

### Combine baseline and amyloid data

``` r
mci_baseline_amyloid_data =
  inner_join(mci_baseline_data, mci_amyloid_data, by = "id")

mci_baseline_amyloid_data
```

    ## # A tibble: 2,355 × 8
    ##       id baseline_age sex    education apoe4   age_at_onset years_since_baseline
    ##    <dbl>        <dbl> <fct>      <dbl> <fct>          <dbl>                <dbl>
    ##  1     1         63.1 female        16 carrier           NA                    0
    ##  2     1         63.1 female        16 carrier           NA                    2
    ##  3     1         63.1 female        16 carrier           NA                    4
    ##  4     1         63.1 female        16 carrier           NA                    6
    ##  5     1         63.1 female        16 carrier           NA                    8
    ##  6     2         65.6 female        20 carrier           NA                    0
    ##  7     2         65.6 female        20 carrier           NA                    2
    ##  8     2         65.6 female        20 carrier           NA                    4
    ##  9     2         65.6 female        20 carrier           NA                    6
    ## 10     2         65.6 female        20 carrier           NA                    8
    ## # ℹ 2,345 more rows
    ## # ℹ 1 more variable: amyloid_42_40_ratio <dbl>

``` r
number_of_participants_in_combined_mci_data =
  mci_baseline_amyloid_data |>
  distinct(id) |>
  pull(id) |>
  length()

number_of_visit_records_in_combined_mci_data =
  length(mci_baseline_amyloid_data$id)

number_of_variables_in_combined_mci_data =
  length(names(mci_baseline_amyloid_data))
```

### Combined dataset description

I joined the eligible baseline and amyloid datasets by `id`, keeping
participants present in both. The result contains 2355 participant-visit
records from 471 participants and 8 variables. Each row is one
participant at one visit, with baseline demographics, MCI onset age,
years since baseline, and the amyloid ratio. Baseline information is
repeated across visits, and missing amyloid ratios remain as `NA`.

### Export the combined data

``` r
write_csv(mci_baseline_amyloid_data, "./data/mci_baseline_amyloid_data.csv")
```
